### ISSUE TITLE
I18nextService.events.languageChanged is not triggered

### ISSUE THREAD

**Issue by david-bulte** [Romanchuk/angular-i18next#27] opened 2019-02-22 12:53 UTC
When I change the language, the languageChanged event doesn't seem to be triggered.

I change the language like so:

```

    setLang(lang) {

    this.i18nextService.changeLanguage(lang).then(evt => {
      console.log("setLang", evt);
    });
  }

```

This changes the language, but the languageChanged event is not triggered. Here is how I listen for this event.

```
    this.i18nextService.events.languageChanged.subscribe(lng => {
      console.log("angular-i18next", lng);
    })

```

When I listen to the event on the underlying i18next implementation, I *do* get notified of the event:

```
    const i18next = i18n.default;

    ...

    i18next.on('languageChanged', (lng) => {
      console.log("i18next - languageChange", lng);
      console.log("this.i18n.events.languageChanged.getValue()", this.i18nextService.events.languageChanged.getValue());
    })

```

That last console.out learns me that the value on the languageChanged BehaviorSubject hasn't been set properly. These are the logs:

> i18next - languageChange nl
> this.i18n.events.languageChanged.getValue() null
> setLang {err: undefined, t: ƒ}

**Comment by Romanchuk** [comment] 2019-03-06 09:09
@david-bulte Hi, what is your versions?
angular
i18next
angular-18next

**Comment by Romanchuk** [comment] 2019-03-06 10:45
Here is demo app runninig on latest version
https://github.com/Romanchuk/angular-i18next-demo
https://romanchuk.github.io/angular-i18next-demo/

**Comment by david-bulte** [comment] 2019-03-06 11:28
My versions:

- "i18next": "^15.0.4",
- "i18next-browser-languagedetector": "^3.0.1",
- "i18next-xhr-backend": "^2.0.1",
- "@angular/core": "^7.2.7",
- "angular-i18next": "^6.0.0"

Here's how I use it. As you see I'm listening to the events in the constructor of a pipe. The console.log('>>>>>> translation', translation); is not carried out.

```
import { ChangeDetectorRef, OnDestroy, OnInit, Pipe, PipeTransform } from '@angular/core';
import { I18NextPipe, I18NextService } from 'angular-i18next';
import * as i18n from 'i18next';

const _i18next = i18n.default;

@Pipe({
  name: 'nexuzhealthI18n',
  pure: false
})
export class I18nPipe implements PipeTransform, OnDestroy {

  private langChanged = this.languageChanged.bind(this);

  constructor(private i18Next: I18NextService, private i18NextPipe: I18NextPipe, private changeDetector: ChangeDetectorRef) {

    // bug? cf. https://github.com/Romanchuk/angular-i18next/issues/27
    this.i18Next.events.languageChanged.subscribe(translation => {
      console.log('>>>>>> translation', translation);
      this.changeDetector.markForCheck();
    })

    _i18next.on('languageChanged', this.langChanged);
  }

  transform(value: any, args?: any): any {
    return this.i18NextPipe.transform(value, args);
  }

  ngOnDestroy(): void {
    _i18next.off('languageChanged', this.langChanged)
  }

  languageChanged(lng) {
    this.changeDetector.markForCheck();
  }
}

```

**Comment by Romanchuk** [comment] 2019-03-11 14:53
I have reproduced it on demo app, it is not a bug. You are injecting "i18Next: I18NextService", but you should inject it throught token like this:

`@Inject(I18NEXT_SERVICE) private i18NextService: ITranslationService
`

I guess the reason is that you have inited i18next module using token (as recommended)
```typescript
{
    provide: APP_INITIALIZER,
    useFactory: appInit,
    deps: [I18NEXT_SERVICE],
    multi: true
  }
```
but then you should inject I18NEXT_SERVICE token everywhere in your app, because you inited it.
You injecting I18NextService, but it was not inited (events was not subscribed).

May be i should depricate I18NextService provider to remove this confusion

**Comment by david-bulte** [comment] 2019-03-12 09:23
This is working much better, thanks! Still I have a little problem. The languageChanged event is not being called in a module that was lazy loaded. I noticed that the ITranslationService instance (now injected via @Inject(I18NEXT_SERVICE)) is not the same in the root as in the (lazy loaded) module, maybe that is the reason?

Here's a snippet of my configuration:

```
@NgModule({
  imports: [CommonModule, I18NextModule.forRoot()],
  declarations: [I18nPipe],
  exports: [I18NextModule, I18nPipe]
})
export class SharedUtilI18nModule {

  static forRoot(config: I18NextConfig = {}): ModuleWithProviders {
    return {
      ngModule: SharedUtilI18nModule,
      providers: [
        {provide: i18next_config, useValue: config},
        {
          provide: APP_INITIALIZER,
          useFactory: appInit,
          deps: [I18NEXT_SERVICE, i18next_config],
          multi: true
        }
      ]
    }
  }

}

```

In my (root) AppModule, I use this like so:

`SharedUtilI18nModule.forRoot({ns: {ns: ['gp', 'auth', 'common'], merge: true}})
`

While in the lazy-loaded module, I just import SharedUtilI18nModule (to be able to use the i18next pipe).

What am I doing wrong? Is it normal that the ITranslationService isn't a singleton?

**Comment by Romanchuk** [comment] 2019-03-12 12:55
ITranslationService is a singleton, but in your lazy module there is the other Injector, that has no instances of ITranslationService and it creates it own (the new one).
I have in my projects lazy modules and i do it like this:
- AppModule: import I18NextModule.forRoot(..)
- Lazy module: import I18NextModule to provide pipes. ITranslationService would be refenced to root ITranslationService and it will be single for whole app.

In your case you should divide your SharedUtilI18nModule and I18NextModule.forRoot, init I18NextModule in AppModule.
SharedUtilI18nModule is only for your pipes and it still imports I18NextModule (without forRoot). And it don't need to export I18NextModule.
InboxPageComponent imports both I18NextModule and SharedUtilI18nModule

------------
The main thing i don't understand: Why do you do it? Why don't you use already implemented mecanisms?

**Comment by david-bulte** [comment] 2019-03-12 13:09
I will try it out later. As for your question, I was looking for a way to dynamically change the translations: you change the language and all translations are immediately refreshed, also the ones in components with ChangeDetection.OnPush (comparable to the AsyncPipe). But maybe you know another way ? :)

**Comment by Romanchuk** [comment] 2019-03-12 17:25
Here are the reasons why i left idea on making pipes dynamic/impure:
https://github.com/Romanchuk/angular-i18next/pull/11#issuecomment-364725022
In early versions i tryied to implement impure pipes, but left this idea for several reasons:

1.  Some custom controls or pipes can be dependent on angular LOCALE_ID token. So we want to change angular LOCALE_ID with i18next language. 
```
{
 provide: LOCALE_ID,
 deps: [I18NextService],
 useFactory: (i18next: I18NextService) => {
  return i18next.language; //string: 'en', 'ru'...
 }
}
```
  The problem is that angular IOC container resolves dependencies as singleton, once LOCALE_ID was     requested it will always resolve as the same value (first resolved). The only way to get actual LOCALE_ID value is to register LOCALE_ID as [factory function](https://angular.io/guide/dependency-injection#factory-providers), but than it will break libraries that expect LOCALE_ID to be 'string' (not function).
 Here is my stackoverflow question: [Dynamicly get LOCALE_ID (resolve per request)](https://stackoverflow.com/questions/41820714/angular-2-dynamicly-get-locale-id-resolve-per-request)

2. Custom components with own localization support mostly require complete reinit on language change.

3. Also most l10n, i18n and date format (momentjs) angular pipes are pure, and changing i18next language or LOCALE_ID won't trigger pipe change detection for them. 

4. Possible memory leaks and perfomant issues. For example zonejs automatically trigger change detection as a result of async operations, this means using jquery libs with ajax could cause your page (full of impure pipes) freeze.

That is why i ended up with simply refreshing page with a new language. We only need to setup right language, locale and formats on angular initialization.

---------------

Also i had impure i18next pipe implementation that was statefull - it had memoisation that returned already translated result if input params and language did not change. It worked well. But in my real world projects language changed immediately, but "angular moment " pipes was not called (they are pure), third party controls also needed to be manually reinit...


This experience i had more than one year ago (with angular v2), maybe today it's more possible) i would like to see implementation that would resolve problems that i mentioned above

**Comment by DevDemba** [comment] 2019-03-26 09:13
Hello, I'm an apprentice developer. I would like to have several values that I return from my database for the same Angular interpolation variable. 
What is i18next capable of solving this problem?

Here is my configuration in app module :
export function appInit(i18next: ITranslationService) {
  
  return () => i18next
  .use(detector)
  .use(backend)
  .use(sprintf)
  .init({
      whitelist: ['en', 'fr'],
      fallbackLng: 'en',
      debug: true,
      returnEmptyString: false,
      returnObjects: true,
      ns: [
        'translation'         
      ],
      backend: {
        loadPath: "./assets/i18n/{{lng}}/{{ns}}.json"
      },
      lng: 'fr',

      // overloadTranslationOptionHandler: sprintf.overloadTranslationOptionHandler,
    });
}

export function localeIdFactory(i18next: ITranslationService)  {
  return i18next.language;
}

export const I18N_PROVIDERS = [
  {
      provide: APP_INITIALIZER,
      useFactory: appInit,
      deps: [I18NEXT_SERVICE],
      multi: true
  },
  {
      provide: LOCALE_ID,
      deps: [I18NEXT_SERVICE],
      useFactory: localeIdFactory
  }];
![image](https://user-images.githubusercontent.com/38429183/54984345-faac2400-4fae-11e9-88e4-c045fe4fee1b.png)
![Annotation 2019-03-26 101017](https://user-images.githubusercontent.com/38429183/54984710-ba997100-4faf-11e9-9140-13ee3c8a0f33.png)



this is my JSON "translation.json":

  "models": {
        "contacts": {
            "attributes": {
                "roles": {
                    "author": "Auteur",
                    "custodian": "Administrateur",
                    "distributor": "Distributeur",
                    "originator": "Créateur",
                    "owner": "Propriétaire",
                    "pointOfContact": "Point de contact",
                    "principalInvestigator": "Analyste principal",
                    "processor": "Responsable du traitement",
                    "publisher": "Éditeur (publication)",
                    "resourceProvider": "Fournisseur",
                    "user": "Utilisateur"
                }
            }
        },

here is my HTML:

 <div class="card info-section-card" *ngFor="let author_or_user of authors_n_users">
                        <b>{{ 'hello author_or_user.role' | i18next }}</b>
                        <p>
                            <i>{{ author_or_user.contact.name }}</i>
                            <br> {{ author_or_user.contact.addressLine1OrNull }}
                            <br> {{ author_or_user.contact.cityOrNull }}, {{ author_or_user.contact.zipCodeOrNull }}
                            <br> {{ author_or_user.country }}
                            <br> {{ author_or_user.contact.phoneNumberOrNull }}
                            <br><a href="mailto:{{ authors_n_users[0].contact.emailOrNull }}">{{ author_or_user.contact.emailOrNull }}</a>
                        </p>
                    </div>

**Comment by Romanchuk** [comment] 2019-03-26 11:13
@DevDemba Hello, i'm not sure i understand what are you trying to do and what is your problem.

**Comment by DevDemba** [comment] 2019-03-26 13:57
Hello, look at my screenshot.
In my contact block, I want to display a different role for each iteration (for each block displayed on the front) based on the filter values of my API. 

I managed to translate the standard variables but not the variables where the values are random. 
I would like to put interpolation variables in my json eventually in order to select a translation to apply according to the filtered role.

thanks

**Comment by Romanchuk** [comment] 2019-03-28 08:55
@DevDemba Did you tried to concat key and translate it?
```{{ ('models.contacts.attributes.roles' + roleVariable) | i18next }}```

**Comment by DevDemba** [comment] 2019-03-28 11:07
@Romanchuk  Yes exactly but it doesn't work the interpolation with the variable "roleVariable".
I need my "roleVariable" to be of the type: {{ roleVariable }} because it comes from a table because I need the key to the role.

**Comment by Romanchuk** [comment] 2019-03-29 05:32
You are welcome.
Closing issue

**Closed by Romanchuk** 2019-03-29 05:32 UTC

**Comment by koza-tavisca** [comment] 2020-01-21 12:39
sorry I have posted quetion on wrong github repo I think my question is related to this conversation here it is can anyone please help I am trying for 4 days now
