### ISSUE TITLE
Backend missing files prevents angular app from starting, when fallback should be applied

### ISSUE THREAD

**Issue by Merwer** [Romanchuk/angular-i18next#9] opened 2017-11-30 15:26 UTC
As per the issue listed at https://github.com/i18next/i18next-xhr-backend/issues/261, if a file is missing, the i18next-xhr-backend issues an error message to the callback indicating the missing files.

The system would normally continue with a graceful fallback, but due to the handling by `I18NextService` in init the app initialization is rejected.

https://github.com/Romanchuk/angular-i18next/blob/6e86224e851a53e9607f1b80dab91aeca90ecdbf/src/I18NextService.ts#L38-L42

When using this project in the app initialization as defined in the cookbook section of the README (https://github.com/Romanchuk/angular-i18next#initialize-i18next-before-angular-application), the `reject` prevents the angular app from initializing, and only a blank screen is presented.

**Comment by Romanchuk** [comment] 2017-12-02 08:37
Thank you for info.
The issue is about fallback to generic culture (en) if there is no specific culture translation file loaded (en-US). Fix me if i am missunerstood you.
I'm going to dive into problem in a next week.

Temporary fix for this case is to wrap init promise in a new promise and resolve both positive and negative results.

**Comment by Romanchuk** [comment] 2017-12-05 14:48
@Merwer i've reproduced an issue. Library should behave as i18next framework.
In the upcomming version (3.0) i'm going to change this behavior to be the same as native and set it by default.
Current strict error handling would be also available to be set with a parameter.

**Comment by Merwer** [comment] 2017-12-05 17:17
@Romanchuk Thanks for the quick response. I'm glad you were able to reproduce the issue, and I think your proposed solution would work out perfectly.

**Comment by Romanchuk** [comment] 2017-12-06 15:55
@Merwer 
version 3.0.0-alpha.2 with a new feature ErrorHandlingStrategy now available.
[https://github.com/Romanchuk/angular-i18next#other-breaking-changes](https://github.com/Romanchuk/angular-i18next#other-breaking-changes)
npm install angular-i18next@3.0.0-alpha.2

**Comment by Romanchuk** [comment] 2017-12-15 13:36
angular-i18next v3.0.0 released

**Closed by Romanchuk** 2017-12-15 13:36 UTC
